# -*- coding: utf-8 -*-
"""HW9Part2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wyBOHVMmzIG7vVZdOn7X0TrGvzZa3Eiz
"""

#Matthew Bitter
#MCS-DS - HW9
#May 7th, 2018
#Google Colab code to run CIFAR10 part of the assignment using Tesla GPU

#This is to link my Google Drive with Google Colab

# Install a Drive FUSE wrapper.
# https://github.com/astrada/google-drive-ocamlfuse
!apt-get install -y -qq software-properties-common python-software-properties module-init-tools
!add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
!apt-get update -qq 2>&1 > /dev/null
!apt-get -y install -qq google-drive-ocamlfuse fuse
# Generate auth tokens for Colab
from google.colab import auth
auth.authenticate_user()
# Generate creds for the Drive FUSE library.
from oauth2client.client import GoogleCredentials
creds = GoogleCredentials.get_application_default()
import getpass
!google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL
vcode = getpass.getpass()
!echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret}

#assign google drive and p drive
!mkdir -p drive
!google-drive-ocamlfuse drive

#Set my default root directory in google colab to where I store my code on my google drive
import sys
import os

sys.path.insert(0, 'drive/Masters/Courses/CS498/Assignments/HW9CF/cifar10')
os.chdir("drive/Masters/Courses/CS498/Assignments/HW9CF/cifar10")

#The tutorial code did not work in TF 1.8 so I downgraded to 1.4
!pip install tensorflow-gpu==1.4.1

#Running the actual code using GPU
!python cifar10_train.py

!ls